version: "3"
services:
  work:
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    image: "mcr.microsoft.com/vscode/devcontainers/base:debian-11"
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres-data: